<script setup lang="ts">
import { computed, ref } from 'vue';
import Icon from '../components/Icon.vue';
import { data, activeEmployees, pendingTasks, openJobs, headcountBudget, navigate, avatarStyle, dateLabel, stageNames, exportCsv } from '../store';
const chartMode = ref('部门');
const taskTab = ref('全部');
const selectedDay = ref(data.meta.referenceDate);
const work = computed(() => taskTab.value==='全部' ? pendingTasks.value : pendingTasks.value.filter(t => t.category===taskTab.value));
const activeFlows = computed(() => data.lifecycles.filter(l => l.status==='进行中'));
const grouped = computed(() => chartMode.value==='部门' ? data.departments.map(d => ({ name:d.name, count:activeEmployees.value.filter(e=>e.department===d.name).length, budget:d.headcountBudget })) : Array.from(new Set(activeEmployees.value.map(e=>e.location))).map(name=>({name,count:activeEmployees.value.filter(e=>e.location===name).length,budget:0})).filter(d=>d.count));
const chartMax = computed(()=>Math.max(1,...grouped.value.flatMap(d=>[d.count,d.budget])));
const days = computed(() => {
  const current = new Date(data.meta.referenceDate + 'T00:00:00Z');
  const monday = new Date(current); monday.setUTCDate(current.getUTCDate() - (current.getUTCDay() + 6) % 7);
  return Array.from({length:7}, (_, i) => {const d = new Date(monday); d.setUTCDate(monday.getUTCDate()+i); return {date:d.toISOString().slice(0,10),day:d.getUTCDate()};});
});
const calendarMonth = computed(()=>data.meta.referenceDate.slice(0,7).replace('-','年')+'月');
const referenceLabel = computed(()=>new Date(data.meta.referenceDate+'T00:00:00Z').toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long',timeZone:'UTC'}));
const dayEvents = computed(()=>data.events.filter(e=>e.date===selectedDay.value));
const deficit = computed(()=>data.departments.map(d=>({...d,gap:d.headcountBudget-activeEmployees.value.filter(e=>e.department===d.name).length})).sort((a,b)=>b.gap-a.gap)[0]);
function exportOverview() { exportCsv('人力工作台概览.csv',['指标','数值'],[['在职员工',activeEmployees.value.length],['编制预算',headcountBudget.value],['在招职位',openJobs.value.length],['待处理事项',pendingTasks.value.length],['进行中异动',activeFlows.value.length]]); }
</script>
<template>
  <section class="welcome-row"><div><div class="greeting"><Icon name="sun" :size="17"/> {{ referenceLabel }}</div><h1>早上好，{{ data.meta.user.name }}<span class="greeting-dot">.</span></h1><p>今天有 <strong>{{ pendingTasks.length }} 项待办</strong> 等你处理，一起让工作有序发生。</p></div><div class="heading-actions"><button class="btn" @click="exportOverview"><Icon name="download" :size="17"/>导出概览</button><button class="btn btn-primary" @click="navigate('recruitment')"><Icon name="plus" :size="18"/>发起招聘</button></div></section>
  <div class="overview-tabs"><button class="active">工作概览</button><button @click="navigate('tasks')">我的待办<span>{{ pendingTasks.length }}</span></button><button @click="navigate('analytics')">人力洞察</button><div class="overview-tabs-end"><span class="live-dot"></span>{{ data.meta.demo ? '工作空间已就绪' : '工作空间已就绪' }}</div></div>
  <section class="metric-row dashboard-metrics">
    <button class="metric-card" @click="navigate('people')"><div class="metric-top"><span class="metric-label">在职员工</span><span class="metric-icon blue"><Icon name="users" :size="20"/></span></div><div class="metric-value">{{ activeEmployees.length }}<span>人</span></div><div class="metric-foot"><span class="badge badge-green">组织规模</span><span>含 {{ activeEmployees.filter(e=>e.status==='试用').length }} 位试用期员工</span></div></button>
    <button class="metric-card" @click="navigate('recruitment')"><div class="metric-top"><span class="metric-label">在招职位</span><span class="metric-icon violet"><Icon name="briefcase" :size="20"/></span></div><div class="metric-value">{{ openJobs.length.toString().padStart(2,'0') }}<span>个</span></div><div class="metric-foot"><span class="badge badge-blue">招聘进行中</span><span>{{ data.candidates.filter(c=>c.stage!=='已淘汰').length }} 位活跃候选人</span></div></button>
    <button class="metric-card" @click="navigate('lifecycle')"><div class="metric-top"><span class="metric-label">员工异动</span><span class="metric-icon teal"><Icon name="transfer" :size="20"/></span></div><div class="metric-value">{{ activeFlows.length.toString().padStart(2,'0') }}<span>项</span><div class="mini-avatars"><span v-for="flow in activeFlows.slice(0,3)" :key="flow.id" class="avatar" :style="avatarStyle(flow.name)">{{ flow.name.slice(-1) }}</span></div></div><div class="metric-foot"><span class="badge badge-muted">正在办理</span><span>{{ activeFlows.filter(f=>f.type==='入职').length }} 入职 · {{ activeFlows.filter(f=>f.type==='转正').length }} 转正</span></div></button>
    <button class="metric-card" @click="navigate('tasks')"><div class="metric-top"><span class="metric-label">待处理事项</span><span class="metric-icon amber"><Icon name="tasks" :size="20"/></span></div><div class="metric-value">{{ pendingTasks.length.toString().padStart(2,'0') }}<span>项</span><span class="metric-priority"><Icon name="clock" :size="15"/>{{ pendingTasks.filter(t=>t.priority==='紧急').length }} 项紧急</span></div><div class="metric-foot"><span class="badge badge-amber">需要关注</span><span>及时响应，协同更顺畅</span></div></button>
  </section>
  <div class="dashboard-grid">
    <section class="panel workforce-panel"><div class="panel-header"><div><h2>团队规模与编制<span class="tiny-label">WORKFORCE</span></h2><p>看见团队现状，让人才配置更有方向</p></div><div class="segmented"><button v-for="mode in ['部门','地点']" :key="mode" :class="{active:chartMode===mode}" @click="chartMode=mode">{{ mode }}</button></div></div><div class="workforce-summary"><div><strong>{{ activeEmployees.length }}</strong><span>当前在职</span></div><span class="summary-divider"></span><div><strong class="light-number">{{ headcountBudget }}</strong><span>编制预算</span></div><div class="chart-legend"><span><i></i>实际人数</span><span v-if="chartMode==='部门'"><i class="pale"></i>编制预算</span></div></div><div class="bar-chart" :aria-label="chartMode+'人数与编制柱状图'"><div class="chart-grid-lines"><i v-for="n in 4" :key="n"></i></div><div v-for="group in grouped" :key="group.name" class="chart-column"><div class="bar-pair"><div class="bar actual" :style="{height:(group.count/chartMax*134)+'px'}" :title="group.name+' 在职 '+group.count+' 人'"><span>{{ group.count }}</span></div><div v-if="group.budget" class="bar budget" :style="{height:(group.budget/chartMax*134)+'px'}" :title="group.name+' 编制 '+group.budget+' 人'"></div></div><span class="chart-x-label">{{ group.name }}</span></div></div><div class="panel-bottom"><span><Icon name="insight" :size="17"/>当前编制使用率 {{ Math.round(activeEmployees.length / (headcountBudget || 1) * 100) }}%，{{ Math.max(0,headcountBudget-activeEmployees.length) }} 个编制待补充</span><button class="text-button" @click="navigate('organization')">查看编制<Icon name="arrowRight" :size="15"/></button></div></section>
    <section class="insight-panel"><div class="insight-top"><span class="insight-emblem"><Icon name="insight" :size="20" weight="duotone"/></span><span>值得关注</span><span class="insight-label">组织脉搏</span></div><h2>从数据出发，<br/>迈出下一步。</h2><p class="insight-intro">你的团队变化，都在这里。</p><button class="insight-item" @click="navigate('recruitment')"><span class="insight-item-icon"><Icon name="briefcase" :size="18"/></span><div><strong>{{ deficit?.name }}还有 {{ Math.max(0,deficit?.gap||0) }} 个编制缺口</strong><p>核对岗位优先级，推进关键人才招聘</p></div><Icon name="chevronRight" :size="16"/></button><button class="insight-item" @click="navigate('lifecycle')"><span class="insight-item-icon"><Icon name="userPlus" :size="18"/></span><div><strong>{{ activeFlows.filter(f=>f.type==='入职').length }} 位新同事正在准备加入</strong><p>检查入职清单，准备好第一天</p></div><Icon name="chevronRight" :size="16"/></button><div class="insight-footer"><span class="insight-line"></span>基于当前业务数据的规则提示</div></section>
    <section class="panel todo-panel"><div class="panel-header"><div class="title-inline"><h2>我的待办</h2><span class="count-pill">{{ pendingTasks.length }}</span></div><button class="text-button muted" @click="navigate('tasks')">全部事项<Icon name="arrowUpRight" :size="16"/></button></div><div class="task-tabs"><button v-for="tab in ['全部','审批','招聘','员工','绩效']" :key="tab" :class="{active:taskTab===tab}" @click="taskTab=tab">{{ tab }}</button></div><div class="dashboard-task-list"><button v-for="task in work.slice(0,4)" :key="task.id" class="dashboard-task" @click="navigate('tasks')"><span class="task-category-icon" :class="task.category==='审批'?'orange':task.category==='绩效'?'purple':''"><Icon :name="task.category==='招聘'?'briefcase':task.category==='员工'?'users':task.category==='绩效'?'target':'file'" :size="19"/></span><span class="task-main"><strong>{{ task.title }}<span v-if="task.priority==='紧急'" class="urgent-label">紧急</span></strong><small>{{ task.subject }}<span>·</span>{{ task.department }}</small></span><span class="task-due">{{ dateLabel(task.dueDate) }}<small>截止日期</small></span><Icon name="chevronRight" :size="16"/></button><div v-if="!work.length" class="empty-state compact"><Icon name="checkCircle" :size="30"/><p>这个分类下的待办已处理完毕</p></div></div></section>
    <section class="panel calendar-panel"><div class="panel-header"><h2>本周日程</h2><span class="calendar-month">{{ calendarMonth }}<Icon name="calendar" :size="16"/></span></div><div class="week-strip"><button v-for="(day,i) in days" :key="day.date" :class="{selected:selectedDay===day.date,weekend:i>4}" @click="selectedDay=day.date"><small>{{ ['一','二','三','四','五','六','日'][i] }}</small><strong>{{ day.day }}</strong><i v-if="data.events.some(e=>e.date===day.date)"></i></button></div><div class="event-list"><div v-for="(event,i) in dayEvents" :key="event.id" class="calendar-event" :class="{purple:i%2}"><span class="event-time">{{ event.time }}</span><div><strong>{{ event.title }}</strong><small>{{ event.participants }}</small></div></div><div v-if="!dayEvents.length" class="calendar-empty"><Icon name="calendar" :size="24"/><p>这一天没有安排</p><span>留一点时间，专注重要的事</span></div></div><div class="calendar-caption">{{ data.meta.demo ? '日程以演示工作周展示' : '日程以数据基准周展示' }}</div></section>
    <section class="panel pipeline-panel"><div class="panel-header"><div><h2>招聘进行时<span class="tiny-label">TALENT PIPELINE</span></h2><p>每一步推进，都离合适的人更近</p></div><button class="text-button muted" @click="navigate('recruitment')">招聘看板<Icon name="arrowUpRight" :size="16"/></button></div><div class="pipeline-stages"><button v-for="(stage,i) in stageNames" :key="stage" @click="navigate('recruitment')"><div class="pipeline-stage-title"><i :style="{background:['#9ab0fa','#7594f2','#5276e6','#8490d4','#4fa99b'][i]}"></i>{{ stage }}</div><strong>{{ data.candidates.filter(c=>c.stage===stage).length.toString().padStart(2,'0') }}</strong><span>位候选人</span><Icon v-if="i<4" class="pipeline-arrow" name="chevronRight" :size="17"/></button></div></section>
    <section class="panel quick-panel"><div class="panel-header"><h2>常用操作</h2><Icon name="stack" :size="18"/></div><div class="quick-grid"><button @click="navigate('people')"><span class="quick-icon blue"><Icon name="userPlus"/></span>员工档案</button><button @click="navigate('lifecycle')"><span class="quick-icon teal"><Icon name="path"/></span>入职办理</button><button @click="navigate('performance')"><span class="quick-icon violet"><Icon name="target"/></span>绩效评审</button><button @click="navigate('analytics')"><span class="quick-icon amber"><Icon name="chart"/></span>人力报表</button></div></section>
  </div>
</template>
