<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import Icon from '../components/Icon.vue';
import Modal from '../components/Modal.vue';
import ResumePreview from '../components/ResumePreview.vue';
import { data, mutate, busy, stageNames, avatarStyle, openJobs, dateLabel } from '../store';
import type { Candidate } from '../types';
const tab = ref('候选人看板');
const jobFilter = ref('');
const search = ref('');
const formMode = ref<'job'|'candidate'|null>(null);
const selectedId = ref('');
const selected = computed(()=>data.candidates.find(c=>c.id===selectedId.value));
const form = reactive({name:'',jobId:'',source:'内推',experience:'3 年',tags:'',title:'',department:'技术研发',level:'P6',location:'北京',headcount:1,owner:'林悦',salaryRange:'25–35K · 16薪'});
const candidates = computed(()=>data.candidates.filter(c=>(!jobFilter.value||c.jobId===jobFilter.value)&&(!search.value||c.name.includes(search.value)||jobTitle(c.jobId).includes(search.value))));
const jobTitle = (id:string)=>data.jobs.find(j=>j.id===id)?.title || '未关联职位';
function openForm(mode:'job'|'candidate') { formMode.value=mode; form.name=''; form.title=''; form.department=data.departments[0]?.name||''; form.tags=''; form.jobId=jobFilter.value||openJobs.value[0]?.id||''; }
async function save() { let okay; if(formMode.value==='job') okay=await mutate('/jobs',{title:form.title,department:form.department,level:form.level,location:form.location,headcount:Number(form.headcount),owner:form.owner,salaryRange:form.salaryRange},'POST','招聘职位已创建'); else okay=await mutate('/candidates',{name:form.name,jobId:form.jobId,source:form.source,experience:form.experience,tags:form.tags.split(/[，,]/).map(t=>t.trim()).filter(Boolean)},'POST','候选人已加入招聘看板'); if(okay)formMode.value=null; }
async function advance(candidate:Candidate, reject=false) { const next=reject?'已淘汰':stageNames[stageNames.indexOf(candidate.stage)+1]; if(!next)return; const okay=await mutate(`/candidates/${candidate.id}/stage`,{stage:next},'PATCH',next==='待入职'?'已创建员工档案与入职清单':`候选人已转入${next}`); if(okay)selectedId.value=''; }
</script>
<template>
  <div class="page-heading"><div><span class="eyebrow">TALENT ACQUISITION</span><h1>招聘管理</h1><p class="page-subtitle">连接业务需求与合适的人，让每一次招聘都有进展。</p></div><div class="heading-actions"><button class="btn" @click="openForm('candidate')"><Icon name="userPlus" :size="18"/>添加候选人</button><button class="btn btn-primary" @click="openForm('job')"><Icon name="plus" :size="18"/>新建职位</button></div></div>
  <div class="recruit-summary"><div><span>在招职位</span><strong>{{ openJobs.length }}<small>个</small></strong></div><div><span>计划招聘</span><strong>{{ openJobs.reduce((n,j)=>n+j.headcount,0) }}<small>人</small></strong></div><div><span>活跃候选人</span><strong>{{ data.candidates.filter(c=>c.stage!=='已淘汰').length }}<small>位</small></strong></div><div><span>Offer 沟通中</span><strong>{{ data.candidates.filter(c=>c.stage==='Offer').length }}<small>位</small></strong></div><div class="recruit-note"><Icon name="briefcase" :size="30" weight="duotone"/><span>让关键岗位，<br/><strong>遇见关键人才。</strong></span></div></div>
  <section class="panel recruitment-panel"><div class="toolbar"><div class="underlined-tabs"><button v-for="t in ['候选人看板','招聘职位','已淘汰']" :key="t" :class="{active:tab===t}" @click="tab=t">{{ t }}</button></div><div class="toolbar-right"><label class="search-field"><Icon name="search" :size="17"/><input v-model="search" placeholder="搜索候选人或职位" aria-label="搜索候选人或职位"/></label><select v-model="jobFilter" class="select-field" aria-label="职位筛选"><option value="">全部职位</option><option v-for="job in data.jobs" :key="job.id" :value="job.id">{{ job.title }}</option></select></div></div>
    <div v-if="tab==='候选人看板'" class="kanban-scroll"><div class="kanban"><section v-for="(stage,index) in stageNames" :key="stage" class="kanban-column"><header><span class="stage-dot" :style="{background:['#99a9d8','#7594f2','#5276e6','#ad8acf','#58a597'][index]}"></span><h2>{{ stage }}</h2><span class="stage-count">{{ candidates.filter(c=>c.stage===stage).length }}</span></header><button v-for="candidate in candidates.filter(c=>c.stage===stage)" :key="candidate.id" class="candidate-card" @click="selectedId=candidate.id"><div class="candidate-top"><span class="avatar" :style="avatarStyle(candidate.name)">{{ candidate.name.slice(-1) }}</span><div><strong>{{ candidate.name }}</strong><small>{{ candidate.experience }}经验</small></div><Icon name="more" :size="20"/></div><h3>{{ jobTitle(candidate.jobId) }}</h3><div class="candidate-tags"><span v-for="tag in candidate.tags.slice(0,2)" :key="tag">{{ tag }}</span></div><footer><span>{{ candidate.source }}</span><span>{{ dateLabel(candidate.appliedAt) }}</span></footer></button><div v-if="!candidates.some(c=>c.stage===stage)" class="kanban-empty">暂无候选人</div></section></div></div>
    <div v-else-if="tab==='招聘职位'" class="table-wrap"><table><thead><tr><th>职位名称</th><th>所属部门</th><th>工作地点</th><th>招聘名额</th><th>候选人</th><th>状态</th><th>负责人</th></tr></thead><tbody><tr v-for="job in data.jobs.filter(j=>(!jobFilter||j.id===jobFilter)&&(!search||j.title.includes(search)))" :key="job.id"><td><button class="table-link" @click="jobFilter=job.id;tab='候选人看板'">{{ job.title }}</button><small class="cell-subtitle">{{ job.level }} · {{ job.salaryRange }}</small></td><td>{{ job.department }}</td><td>{{ job.location }}</td><td>{{ job.headcount }} 人</td><td>{{ data.candidates.filter(c=>c.jobId===job.id&&c.stage!=='已淘汰').length }} 位</td><td><span class="badge badge-green">{{ job.status }}</span></td><td>{{ job.owner }}</td></tr></tbody></table><div v-if="!data.jobs.some(j=>(!jobFilter||j.id===jobFilter)&&(!search||j.title.includes(search)))" class="empty-state"><p>没有符合条件的职位</p></div></div>
    <div v-else class="rejected-list"><button v-for="candidate in candidates.filter(c=>c.stage==='已淘汰')" :key="candidate.id" class="list-row" @click="selectedId=candidate.id"><span class="avatar" :style="avatarStyle(candidate.name)">{{ candidate.name.slice(-1) }}</span><span><strong>{{ candidate.name }}</strong><small>{{ jobTitle(candidate.jobId) }}</small></span><span class="badge badge-muted">已淘汰</span><Icon name="chevronRight" :size="18"/></button><div v-if="!candidates.some(c=>c.stage==='已淘汰')" class="empty-state"><Icon name="users" :size="32"/><p>暂无已淘汰候选人</p></div></div>
  </section><p class="data-note"><Icon name="insight" :size="15"/>看板展示候选人的当前阶段；Offer 确认进入待入职后，自动创建员工档案与入职清单。</p>
  <Modal v-if="selected" wide :title="selected.name+' · 候选人详情'" :subtitle="jobTitle(selected.jobId)" @close="selectedId=''"><div class="candidate-profile"><span class="avatar large" :style="avatarStyle(selected.name)">{{ selected.name.slice(-1) }}</span><div><h3>{{ selected.name }}</h3><span class="badge badge-blue">{{ selected.stage }}</span></div></div><ResumePreview :candidate="selected" :job="jobTitle(selected.jobId)"/><dl class="detail-grid"><div><dt>招聘职位</dt><dd>{{ jobTitle(selected.jobId) }}</dd></div><div><dt>工作经验</dt><dd>{{ selected.experience }}</dd></div><div><dt>人才渠道</dt><dd>{{ selected.source }}</dd></div><div><dt>进入时间</dt><dd>{{ selected.appliedAt }}</dd></div></dl><div class="candidate-tags profile-tags"><span v-for="tag in selected.tags" :key="tag">{{ tag }}</span></div><div v-if="selected.stage==='Offer'" class="info-banner"><Icon name="userPlus"/><p>确认候选人接受 Offer 后再推进。系统将建立待入职员工档案，并创建入职准备清单。</p></div><div v-if="selected.stage==='待入职'" class="info-banner"><Icon name="checkCircle"/><p>入职协同已开启，请前往「入转调离」跟进资料、设备和导师安排。</p></div><template #footer><button class="btn" @click="selectedId=''">关闭</button><button v-if="!['待入职','已淘汰'].includes(selected.stage)" class="btn btn-danger-text" :disabled="busy" @click="advance(selected,true)">淘汰</button><button v-if="!['待入职','已淘汰'].includes(selected.stage)" class="btn btn-primary" :disabled="busy" @click="advance(selected)">{{ selected.stage==='Offer'?'确认接受，转入职':'推进至'+stageNames[stageNames.indexOf(selected.stage)+1] }}<Icon name="arrowRight" :size="16"/></button></template></Modal>
  <Modal v-if="formMode" :title="formMode==='job'?'新建招聘职位':'添加候选人'" :subtitle="formMode==='job'?'从清晰的人才需求开始':'建立人才档案，进入简历筛选阶段'" @close="formMode=null"><form id="recruit-form" class="form-grid" @submit.prevent="save"><template v-if="formMode==='job'"><label class="form-field form-full">职位名称<input v-model.trim="form.title" required maxlength="60" placeholder="例如：高级前端工程师"/></label><label class="form-field">所属部门<select v-model="form.department"><option v-for="department in data.departments" :key="department.id">{{ department.name }}</option></select></label><label class="form-field">职级<input v-model="form.level" required maxlength="20"/></label><label class="form-field">招聘人数<input v-model="form.headcount" type="number" min="1" max="100" step="1" required/></label><label class="form-field">工作地点<select v-model="form.location"><option>北京</option><option>上海</option><option>深圳</option><option>杭州</option><option>成都</option></select></label><label class="form-field">薪资范围<input v-model="form.salaryRange" maxlength="60" placeholder="25–35K · 16薪"/></label><label class="form-field">招聘负责人<input v-model="form.owner" required maxlength="30"/></label></template><template v-else><label class="form-field">候选人姓名<input v-model.trim="form.name" required maxlength="30" placeholder="输入姓名"/></label><label class="form-field">工作经验<input v-model="form.experience" required maxlength="20" placeholder="3 年"/></label><label class="form-field form-full">应聘职位<select v-model="form.jobId" required><option disabled value="">选择招聘职位</option><option v-for="job in openJobs" :key="job.id" :value="job.id">{{ job.title }} · {{ job.department }}</option></select></label><label class="form-field">人才渠道<select v-model="form.source"><option>内推</option><option>招聘网站</option><option>猎头推荐</option><option>校园招聘</option><option>主动寻访</option></select></label><label class="form-field">专业标签<input v-model="form.tags" maxlength="100" placeholder="Vue, TypeScript（逗号分隔）"/></label></template></form><template #footer><button class="btn" @click="formMode=null">取消</button><button class="btn btn-primary" form="recruit-form" type="submit" :disabled="busy">{{ busy?'正在保存…':'确认创建' }}</button></template></Modal>
</template>
