<script setup lang="ts">
import { computed, ref } from 'vue';
import Icon from '../components/Icon.vue';
import { data, exportCsv } from '../store';
const search=ref('');
const audit=computed(()=>data.audit.filter(a=>`${a.action}${a.entity}${a.detail}`.includes(search.value)));
function download(){exportCsv('HR操作审计.csv',['操作','对象','详情','时间'],audit.value.map(a=>[a.action,a.entity,a.detail,a.createdAt]));}
function time(value:string){return new Date(value).toLocaleString('zh-CN',{hour12:false});}
</script>
<template><div class="page-heading"><div><span class="eyebrow">WORKSPACE & AUDIT</span><h1>系统与审计</h1><p class="page-subtitle">清晰的工作空间，每一步操作都有迹可循。</p></div></div><div class="settings-grid"><section class="panel workspace-details"><div class="panel-header"><h2>工作空间信息</h2><span class="badge badge-blue">青禾 People 1.0</span></div><dl class="detail-grid"><div><dt>企业名称</dt><dd>{{ data.meta.company }}</dd></div><div><dt>当前操作人</dt><dd>{{ data.meta.user.name }} · {{ data.meta.user.role }}</dd></div><div><dt>工作空间</dt><dd>{{ data.meta.demo ? '产品体验空间' : '企业工作空间' }}</dd></div><div><dt>统计日期</dt><dd>{{ data.meta.referenceDate }}</dd></div></dl><div class="info-banner"><Icon name="shield"/><p>操作记录支持检索与导出。请在完成工作后退出登录，妥善保管已导出的文件。</p></div></section><section class="panel workspace-details"><div class="panel-header"><h2>使用说明</h2><Icon name="book"/></div><div class="release-help"><h3>从待办开始一天的工作</h3><p>跟进招聘、员工流程与绩效进展，及时处理重要事项。</p><h3>查看候选人简历</h3><p>在招聘看板点击候选人，预览或替换 PDF、图片简历。</p><h3>保持信息清晰可追溯</h3><p>数据示例仅供体验。员工与业务记录可按模块检索和导出。</p></div></section></div><section class="panel audit-panel"><div class="panel-header"><div><h2>操作审计<span class="tiny-label">ACTIVITY LOG</span></h2><p>记录业务变更，方便协作追溯</p></div><button class="btn btn-small" @click="download"><Icon name="download" :size="16"/>导出记录</button></div><div class="toolbar"><label class="search-field"><Icon name="search" :size="17"/><input v-model="search" aria-label="搜索操作记录" placeholder="搜索操作、对象或详情"/></label><span class="muted">当前加载 {{ audit.length }} 条记录</span></div><div class="table-wrap"><table><thead><tr><th>操作类型</th><th>业务对象</th><th>变更详情</th><th>操作时间</th></tr></thead><tbody><tr v-for="entry in audit" :key="entry.id"><td><span class="audit-action"><Icon name="checkCircle" :size="17"/>{{ entry.action }}</span></td><td>{{ entry.entity }}</td><td class="audit-detail">{{ entry.detail }}</td><td class="nowrap">{{ time(entry.createdAt) }}</td></tr></tbody></table><div v-if="!audit.length" class="empty-state"><Icon name="file" :size="32"/><p>{{ search?'没有匹配的操作记录':'完成一次业务操作后，记录将出现在这里' }}</p></div></div></section></template>
